SMS/urls.py
from django.contrib import admin
from django.urls import path
#from . import views

from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
   # path('', views.index, name='home'),
]

facultyapp/urls.py
from django.urls import path,include
from . import views
app_name='facultyapp'
urlpatterns=[
    path('facultyhomepage/', views.facultyhomepage, name='facultyhomepage'),
    path('addblog/',views.addblog,name='addblog'),
    path('<int:pk>/delete/',views.deleteblog,name='deleteblog'),
    path('add-product/', views.add_product, name='add_product'),
]

studentapp/urls.py
from django.urls import path,include
from . import views
app_name='studentapp'
urlpatterns = [
    path('studenthomepage/',views.studenthomepage,name='studenthomepage'),
    path('buyproductspagecall/',views.buyproductspagecall,name='buyproductspagecall'),
    path('buyproductspagelogic/', views.buyproductspagelogic, name='buyproductspagelogic'),
    path('fertilizerpagecall/',views.fertilizerpagecall,name='fertilizerpagecall'),
    path('fertilizerpagelogic/',views.fertilizerpagelogic,name='fertilizerpagelogic'),

]

templates/navbar/facultynavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Vendor Portal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body style="background-color:rgb(219, 222, 55)">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color:rgb(47, 47, 47);">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Vendor Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'facultyapp:facultyhomepage' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Manage Crops</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">View Farmer Progress</a>
                    </li>
                     <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white;">
              vendor Topics
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'facultyapp:addblog' %}">Blog</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
  <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
</svg></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

  {% block body %}
  {% endblock %}
</body>

</html>

templates/navbar/studentnavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Farmer Portal</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Farmer Portal</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'studentapp:studenthomepage' %}">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'studentapp:buyproductspagecall' %}">Sell Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'studentapp:fertilizerpagecall' %}">Buy Fertilizers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Request Help</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Recommendations</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0z"/>
  <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
</svg></a>
                    </li>

                </ul>
            </div>
        </div>

</div>
    </nav>
{% block body %}
  {% endblock %}
</body>
</html>